### ISSUE TITLE
Tracking: spec v0.12.0

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1182]
## Description

This issue tracks our progress on becoming fully compliant with spec [`v0.12.0`](https://github.com/ethereum/eth2.0-specs/releases/tag/v0.12.0).

**The only issue left here is gossipsub v1.1 and it is likely to land in early July. Thankfully, 1.1 is backward-compatible with 1.0 (what we have), so this does not impede multi-client testnets.**

### Testing

- [x] The spec rewards code has been refactored to make testing easier. We'll probably have to update `ValidatorStatuses` to suit (#1228)
  - https://github.com/ethereum/eth2.0-specs/pull/1747
  - https://github.com/ethereum/eth2.0-specs/pull/1826

### Beacon Chain

- [x] Adjust INACTIVITY_PENALTY_QUOTIENT to accurately reflect intention (#1228)
  - https://github.com/ethereum/eth2.0-specs/pull/1712
- [x] Rename SigningRoot to SigningData (#1228)
  - https://github.com/ethereum/eth2.0-specs/pull/1740
- [x] Remove PERSISTENT_ COMMITTEE_PERIOD in favor of SHARD_COMMITTEE_PERIOD ( (#1228)
  - https://github.com/ethereum/eth2.0-specs/pull/1783
- [x] Disallow empty aggregation bits in attestations (#1228)
  - https://github.com/ethereum/eth2.0-specs/pull/1780
- [x] Change MAX_ATTESTER_SLASHINGS from 1 to 2 (#1228)
  - https://github.com/ethereum/eth2.0-specs/pull/1794
- [x] Ensure balances remain unchanged for optimal validators during inactivity leak (#1228)
  - https://github.com/ethereum/eth2.0-specs/pull/1830

### Fork choice

_Note: @paulhauner is current working to resolve these._

- [x] Add FFG-LMD vote consistency checks
  - https://github.com/ethereum/eth2.0-specs/pull/1742
- [x] [Non-substantive] Remove redundant check in validate_on_attestation 
  - https://github.com/ethereum/eth2.0-specs/pull/1755
  - IIRC we have already implemented this but we still a TODO in our code to be resolved when spec updates.
- [x] Fix our long-lasting issues with updating the justified checkpoint.

### Networking

- [x] Require "seen" aggregates to be valid to bound cache (#1236)
  - https://github.com/ethereum/eth2.0-specs/pull/1749
- [x] Clarify beacon committee assignments are not added to attnets ENR entry
  - https://github.com/ethereum/eth2.0-specs/pull/1775
- [x] Remove interop from p2p spec (#1230)
  - https://github.com/ethereum/eth2.0-specs/pull/1767
- [ ] Bump gossipsub to v1.1 and note extended validator enums for gossip conditions
  - https://github.com/ethereum/eth2.0-specs/pull/1796
  - https://github.com/ethereum/eth2.0-specs/pull/1828)
- [x] Clarify blocks in BlocksByRange must be from a single chain
  - https://github.com/ethereum/eth2.0-specs/pull/1795
- [x] Req/Resp sizes constrained by SSZ bounds (#1250)
  - https://github.com/ethereum/eth2.0-specs/pull/1800
- [x] Loosen restrictions for aggregate propagation to not require aggregator in bitfield (#1236)
  - https://github.com/ethereum/eth2.0-specs/pull/1801
- [x] Use all attestation subnets in Phase 0 (#1257)
  - https://github.com/ethereum/eth2.0-specs/pull/804
- [x] Restrict and clarify BlocksByRange request
  - https://github.com/ethereum/eth2.0-specs/pull/1835
- [x] [Verification of gossip items that aren't blocks or attestations.](https://github.com/sigp/lighthouse/blob/d79e07902e8d3daf38fb79cd43436d513ca22675/beacon_node/network/src/router/mod.rs#L290-L307) (#1253)
  - There are rules for gossip validation of exits and slashings in the spec that we haven't yet implemented, see [here](https://github.com/ethereum/eth2.0-specs/blob/v0.12.0/specs/phase0/p2p-interface.md#global-topics).

### SSZ

- [x] Fix bitfield_bytes type error
  - https://github.com/ethereum/eth2.0-specs/pull/1806
  - I don't think we need to change anything, but we should double check. Update: we didn't need to change anything, see #1228.

### BLS

- [x] Update BLS to use IETF bls draft 2 with hash-to-curve draft 7 (#1183)
  -  https://github.com/ethereum/eth2.0-specs/pull/1799

**Comment by paulhauner** [comment]
I'm going to start working on fork choice :)

**Comment by michaelsproul** [comment]
I’ll take the rewards updates and the other consensus updates

**Comment by paulhauner** [comment]
There's also some stuff missing here introduced via the later patches of `v0.11.x`.

**Comment by michaelsproul** [comment]
Planning to squash merge everything into #1227, then merge that to master while retaining its commits. Will tick things off as they make it into PRs.

**Comment by michaelsproul** [comment]
I'm working on the updates related to attestation verification now

**Comment by pawanjay176** [comment]
I'm working on the networking updates.

**Comment by michaelsproul** [comment]
I'll move on to gossip verification for attester/proposer slashings and voluntary exits.

**Comment by michaelsproul** [comment]
I've ticked off the remaining items that have pending or merged PRs, and there are just a few network ones remaining! AFAICT, these are either clarifications that we were already compliant with (the ENRs and `BlocksByRange` stuff), or work that we're planning to complete after the initial v0.12 update/testnets. @AgeManning could you confirm?

We're getting close! :muscle:

**Comment by AgeManning** [comment]
As far as I can tell, all the network parts are either complete or in a PR, with the exception of gossipsub 1.1 which we will add in after this release. 
@pawanjay176 should double confirm that this is correct.

**Comment by pawanjay176** [comment]
All the unchecked networking items(except gossipsub) is something that didn't require any changes.
All networking items would be complete after #1257 is merged.

**Comment by paulhauner** [comment]
> All the unchecked networking items(except gossipsub) didn't require any changes.All networking items would be complete after #1257 is merged.

Thanks @pawanjay176! I'm going to cross of all the remaining network issues except gossipsub.
