### ISSUE TITLE
Tracking: October security review

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1436]
# Description

This issue tracks the features/tasks required *prior* to the NCC/ToB security review in early October.

### New Features

- [ ] #1347: HTTP API for VC.
    - Status: ⏳ Not started.
- [ ] #1434: Implement standard API for BN.
    - Status: 🛠️ WIP #1569
- [ ] #1435: Start from weak-subjectivity state.
    - Status: 🛠️ Preliminary works started (see #1380)
- [x] ~~#1172: Gossipsub 1.1~~
    - ~~Status: Done!~~

### Fixes, improvements, etc.

- [ ] #1394: Validator generation wizard.
    - Status: 🛠️ WIP
- [ ] #1437: Allow for tty/stdin passwords for all account flows.
    - Status: ⏳ Not started.
- [ ] New directory structure for `~/.lighthouse`.
    - Status:  Under review in #1532.
- [ ] Ensure validator client lockfiles are handled correctly.
    - Status: 🛠️ WIP #1586

**Comment by pawanjay176** [comment]
I can work on the directory restructure if no one has started on it yet @paulhauner

**Comment by adaszko** [comment]
> #1435: Start from weak-subjectivity state.
> Assigned: @adaszko (please confirm

Confirming.  I don't have full clarity on the scope of the task and acceptance criteria though.

**Comment by paulhauner** [comment]
> I can work on the directory restructure if no one has started on it yet @paulhauner

Great, thanks @pawanjay176!

**Comment by paulhauner** [comment]
Closing this since I've been using issue tags to track this milestone. I don't think anyone else uses it, feel free to open if you do.
