### ISSUE TITLE
VC GUI: required information

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#1691]
## Description

This is issue tracks the datapoints required for the VC GUI.

It's quite rough now but I'll clean it up.

## Items

- [ ] Sync speed
- [x] Eth1 node connection status (WIP #1797)
  - [x] Sync status (WIP #1797)
  - [x] Sync speed? (WIP #1797)
  - [x] Chain id (add to spec) (WIP #1799)
- [ ] Disk utilization
- [ ] Network bandwidth usage
- [ ] Remove validator
- [ ] Validator exit
- [ ] VC -> BN connection status
- [ ] Balances spec
- [ ] Get blocks by proposer
- [ ] Validator attestations seen/included in chain.
- [ ] Waiting for genesis info.
  - [ ] waiting for deposits
  - [ ] waiting for genesis time
- [ ] Participation metrics
- [ ] System health as "traffic light" (good, medium, bad)

## TODO

- Can we report prom metrics via the API without affecting future reads?=

**Comment by paulhauner** [comment]
Closing since we're going to reboot the VC GUI and this is irrelevant now.
