### ISSUE TITLE
Kintsugi Tracking 🍵

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#2830]
*Kintsugi is the unique and traditional Japanese art of repairing broken, chipped and cracked pottery using lacquer and gold.*

## Description

This is the canonical tracking issue for the Kintsugi 🍵 testnets in November 2021.

Kintsugi Milestones: https://notes.ethereum.org/@djrtwo/kintsugi-milestones
Kintsugi Spec: https://hackmd.io/@n0ble/kintsugi-spec

**The canonical branch for running Kintsugi is [`unstable`](https://github.com/sigp/lighthouse/tree/unstable).**

## Notes to Interop Teams

We're keeping scripts that can run Lighthouse testnets against the EL clients at [sig/lighthouse-kintsugi](https://github.com/sigp/lighthouse-kintsugi).

### Building Lighthouse from Source

You'll need to install Rust, we recommend using the standard [`rustup`](https://www.rust-lang.org/tools/install) tool. The commands here will install the binaries to `~/.cargo/bin`, so you'll need to make sure that's on your `PATH`.

Once you have installed Rust, install Lighthouse with:

```bash
git clone git@github.com:sigp/lighthouse.git
cd lighthouse
git checkout unstable
make
```

*Optional: to get the `lcli` binary, run `make install-lcli`.* 

### Lighthouse via Docker

```bash
docker run sigp/lighthouse:unstable lighthouse --version
```

Sometimes we use `lcli` (Lighthouse CLI) for creating testnets. You can also find it on Dockerhub at [`sigp/lcli:unstable`](https://hub.docker.com/r/sigp/lcli/tags?page=1&ordering=last_updated&name=unstable).

### High Priority (M1)

*M1 Complete*

## Medium Priority

- [ ] Modify proto-array so it may select between verified/non-verified heads.
    - Assigned to @paulhauner
- [ ] Run `validate_merge_block` after-the-fact if we did an optimistic sync.
- [ ] Call preparePayload when block producer is known, prior to producing a block.
- [ ] Add per-endpoint caches for payload ids
- [ ] Ensure JSON-RPC request IDs are strictly increasing.
- [ ] Add tests for new gossip verification conditions (e.g., block execution payload).
- [ ] Review peer scoring for the merge. E.g., types of invalid payloads.

## Low Priority

- [ ] End blocking tasks created by the ExecutionLayer when the shutdown signal is called.
    - @pawanjay176 is working on this.
- [ ] Follow up once Clarification on get_pow_block ethereum/consensus-specs#2636 is resolved.
- [ ] Add tests with a terminal block hash override.
- [ ] Add tests for newly added CLI flags.
- [ ] Enable "block_lookup_failed" EF test once we can retrospectively verify the merge block.

**Comment by paulhauner** [comment]
The `kintsugi` branch has been merged into `unstable` :tada:

All merge testnets should now target the [`unstable`](https://github.com/sigp/lighthouse/tree/unstable) branch.

**Comment by paulhauner** [comment]
This is outdated and #2929 will continue in it's honor.
