### ISSUE TITLE
Builder API Tracking

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#3091]
## Description

This issue is meant to track outstanding work related to the Lighthouse implementation of the [builder spec](https://github.com/ethereum/builder-specs). 

The goal is to make the https://github.com/sigp/lighthouse/tree/builder-api branch available for users, and for outstanding work here will be marked complete as it is merged into that branch. #3134 will remain open because it's already in use by some users and I'll do my best to keep it up to date with the `builder-api` branch. 

- [x] ~~MEV boost JWT Auth~~ not actually necessary, see the linked issue for discussion https://github.com/flashbots/mev-boost/issues/52 
- [x] pre-Bellatrix block support on blinded endpoints  #3134
- [x] support the normal proposal flow using the blinded blocks endpoints  #3134
- [x] Add a local testnet setup to CI for the blinded block proposal flow **without** mev-boost
- [x] ~~Add a local testnet setup to CI for the blinded block proposal flow **with** mev-boost~~ The purpose of this would have been to test lighthouse <> mev-boost compatibility, but because the `mock_builder` includes the `mev-rs` implementation of the builder API I don't actually think this adds much. Feels like we would end up testing `mev-boost` moreso than lighthouse
- [x] Separate the engine api from the builder api because mev-boost no longer forwards engine - work started [here](https://github.com/realbigsean/lighthouse/tree/split-builder-engine-apis) #3294

## Issues

- [x] #3295
- [x] #3296 
- [x] #3297
- [x] #3298
- [x] #3319
- [x] #3337
- [x] #3355
- [x] #3357

**Comment by realbigsean** [comment]
Completed in https://github.com/sigp/lighthouse/pull/3134
