### ISSUE TITLE
EIP-4844 Tracking

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#3625]
## Description

Thanks a lot @dknopik and @mariusVanDerWijden for kick starting the Lighthouse implementation!

The main Lighthouse EIP-4844 branch will be here: https://github.com/sigp/lighthouse/tree/eip4844

This branch currently has a lot of boiler plate implemented but there is still a lot of functionality missing. The goal in the short term is to at least get this branch far enough along to participate in devnets.  I'll write up issues for the tasks listed below and link them here. All the specs are still under development so the info here will likely change. 

#### Primary
- Block and blob processing
  - We could treat blocks as optimistic until blobs are validated
  - A `BlobHandle` similar to `ExecPayloadHandle` but would be for an RPC request and include a channel receiver from gossip 
  - Verifying kzg commintments against transactions - this is specified in gossip and block processing
- Block production
  - Includes kzg proof construction 
  - KZG implementation status
    - https://github.com/benjaminion/c-kzg - from what I can tell no rust bindings yet
    - https://github.com/ralexstokes/kzg
  - `BlobSidecar` signing
  - Implementation of Beacon API changes to support unsigned and signed blob communication
- Gossip validation
  - blob and block validation are currently independent of each other in gossip 
- Make the execution payload into a `superstruct`
  - Mark and Michael have been working on this in our Capella implementation. We will similarly need this because there are new fee market fields in the execution payload.
#### Secondary
- Blob pruning
- Newtype SSZ derive `#[ssz(transparent)]`

## Outstanding Questions
 - Will blocks and blobs be gossiped and RPC'd together? Currently no on the devnet
 - Should we include `BlobsByRoot` in RPC?
 - Should `BlobsByRange` use signed or unsigned blobs?

## Spec Links

- Meta Spec - https://hackmd.io/@protolambda/eip4844-meta
- Execution API - https://github.com/ethereum/execution-apis/pull/197
- Beacon API - Does not exist yet but we'll need something for block production
- Consensus specs - https://github.com/ethereum/consensus-specs/tree/dev/specs/eip4844
- The [EIP](https://eips.ethereum.org/EIPS/eip-4844) itself
- EIP 4844 Devnet repo - https://github.com/Inphi/eip4844-interop

## Other Useful Links

- Prysm implementation notes https://hackmd.io/hZefl5F5RgWXeibgWflRQQ?view
- Notes on whether to couple block and blob in RPC/gossip https://notes.ethereum.org/RLOGb1hYQ0aWt3hcVgzhgQ?view
- General FAQ https://notes.ethereum.org/@vbuterin/proto_danksharding_faq#What-is-proto-danksharding-aka-EIP-4844
- Readiness checklist https://github.com/ethereum/pm/blob/master/Breakout-Room/4844-readiness-checklist.md

**Comment by pawanjay176** [comment]
> Should we include BlobsByRoot in RPC?

I think yes, because in the case when we get a `BeaconBlock` before the `Blob`, we can request for the corresponding `block_root` over RPC similar to how we do for attestations and sync committee messages.

**Comment by xrchz** [comment]
I'd be happy to add Rust bindings to c-kzg if someone at Lighthouse can coordinate on what interface would be good for them. We have a stripped down 4844 specific version of c-kzg in development here, currently adding C# bindings for Nethermind. https://github.com/dankrad/c-kzg/tree/4844/min-bindings

**Comment by realbigsean** [comment]
### Outstanding tasks [Updated Nov. 4th]

Tasks required to join the next devnet:

- [x] KZG crypto WIP by @pawanjay176  https://github.com/sigp/lighthouse/issues/3685
- [x] Blob sync https://github.com/sigp/lighthouse/issues/3686
- [x] Complete blob produciton https://github.com/sigp/lighthouse/issues/3687

Tasks not required to join the next devnet:

- [x] Consensus spec tests https://github.com/sigp/lighthouse/issues/3688
- [x] Local testnet that forks to 4844 https://github.com/sigp/lighthouse/issues/3691
- [x] Execution block generator across forks https://github.com/sigp/lighthouse/issues/3690
- [ ] Builder API https://github.com/sigp/lighthouse/issues/3689

**Comment by realbigsean** [comment]
Closing this as it's stale
