### ISSUE TITLE
Builder API for blobs

### ISSUE THREAD

**Issue by realbigsean** [sigp/lighthouse#3689]
## Description

This hasn't been spec'd out as far as I can tell, but it is something we should keep in mind. https://github.com/flashbots/mev-boost/issues/392

We would at least have to make sure we are following to whatever versioning scheme is implemented in the API, and I wonder if there is apetite for blinded blobs, in which case we'd end up having to make blobs generic over `Payload: AbstractExecPayload`

**Comment by realbigsean** [comment]
Thinking about this further - we will need `blob_kzg_commitments` in the builder bid so we can include them in a block, and we'll probably need to change the response for submitting a signed block to a builder to be changed from an `ExecutionPayload` to a `SignedBeaconBlockAndBlobsSidecar` or at least something that includes blobs and the kzg proof

**Comment by jimmygchen** [comment]
@0xGabi and I have started making changes on the builder spec and hopefully have a draft PR on the builder spec changes soon. I've summarised the discussions so far on this page: https://hackmd.io/@jimmygchen/B1dLR74Io

```mermaid
sequenceDiagram
    participant validator
    participant consensus
    participant mev_boost
    Title: Block Proposal with Builder API (EIP-4844)
    validator->>consensus: GET v2/validator/blinded_blocks/{slot}
    consensus->>mev_boost: GET v1/builder/header/{slot}/{parent_hash}/{pubkey}
    mev_boost-->>consensus: GET v1/builder/header/{slot}/{parent_hash}/{pubkey} response
    Note left of mev_boost: add `blob_kzg_commitments` to response (`SignedBuilderBid`)
    consensus-->>validator: GET v2/validator/blinded_blocks/{slot} response
    Note left of consensus: add `blob_kzg_commitments` to response
    Note over validator: include `blob_kzg_commitments` in block and sign the header
    validator->>consensus: POST beacon/blinded_blocks
    consensus->>mev_boost: POST /eth/v1/builder/blinded_blocks
    mev_boost-->>consensus: POST /eth/v1/builder/blinded_blocks response
    Note left of mev_boost: revealed payload will have to include `blobs_sidecar` and kzg proof
    Note over consensus: construct block and broadcast block
```

**Comment by jimmygchen** [comment]
@0xGabi and I are working on this change, will hopefully have a draft PR soon!

**Comment by jimmygchen** [comment]
## Task Tracking

## Beacon Node

- [x] `produceBlindedBlock` endpoint updates (#4428)
  - [x] Handle new Deneb `BuilderBid` response from builder endpoint (new `BlindedBlobsBundle` type)
  - [x] Build `BlockContents` response (containing `kzg_commitments`, `proof` and `blinded_blob_sidecars`)
- [x] `submitBlindedBlock` endpoint updates
  - [x] Handle `SignedBlockContents` request and forward to builder
  - [x] Handle unblinded `ExecutionPayloadAndBlobsBundle` response from builder endpoint, and publish block

## Validator Client

- [x] Handle `produceBlindedBlock` response from Beacon API (#4428)
- [x] Individual signing of `blinded_blob_sidecars`
- [x] Build `SignedBlockContents` and submit to Beacon API (`submitBlindedBlock`)

**Comment by realbigsean** [comment]
Completed in:
https://github.com/sigp/lighthouse/pull/4607
https://github.com/sigp/lighthouse/pull/4428
