### ISSUE TITLE
The Verge Tracking

### ISSUE THREAD

**Issue by macladson** [sigp/lighthouse#4042]
## Description

Provide compatibilty for Verkle-enabled execution clients by receiving and propagating the `ExecutionWitness` inside the `ExecutionPayload`.

## Useful Links

- Draft spec: https://github.com/ethereum/consensus-specs/pull/3230
- Lighthouse PR: #4891 
- Lodestar PR: https://github.com/ChainSafe/lodestar/pull/5805
- Lighthouse SSZ `Optional` implementation: https://github.com/sigp/ssz_types/pull/13

## Major Tasks
- [x] Implement the `ExecutionWitness` type.
- [x] Implement Optionals in SSZ and replace the instances of `Union[None, T]`.
- [x] Rebase on Capella.
- [ ] Rebase on Deneb.
- [x] Add Electra fork implementation.
- [ ] Add tests.
- [ ] Other unrelated fork additions?

## Kaustinen Testnet
_Pending information..._

## Outstanding Questions

In the `ExecutionWitness`, the `suffix` field inside each `StateSuffixDiff` is defined as a `uint8`. Does this value need to be quoted for consistency with other integer types? Does it also need to be serialized into big-endian hex?

Will there be any other additions into this fork beyond supporting Verkle Trees?
