### ISSUE TITLE
Fix and test fork revert logic

### ISSUE THREAD

**Issue by michaelsproul** [sigp/lighthouse#4198]
## Description

Lighthouse's mechanism for recovering from missed hard forks is currently broken. It is implemented in the `fork_revert` module, but hasn't worked since Altair.

Part of the reason for this is that it is hard to test comprehensively. The ideal test depends on access to _prior versions of Lighthouse_ which aren't available on CI (yet). The test looks something like this:

1. Run a testnet with two types of nodes:
   - Canonical chain: latest Lighthouse version, and fork epoch set for the latest hard fork (e.g. Capella).
   - Stale chain: previous Lighthouse version and _no fork epoch set_.
2. Wait until the testnet has advanced past the configured fork epoch. The canonical chain should continue (and finalize) with new blocks, while the stale chain _also_ continues. The nodes will likely disconnect from each other on P2P.
3. Shut down all the stale nodes and restart them with the latest version of Lighthouse & with the fork epoch configured. Ensure that they don't crash on startup and sync back up to the canonical chain.

There's a lot of local testnet infra described here which is currently not really up to scratch. We likely need changes like #3807 to land first so we can test these scenarios.

There's also a more minor guarantee that we _can_ test on CI without access to prior versions, which is that the current version of Lighthouse can revert a fork missed by the same version. We could likely test this as a beacon_chain test and it would get us ~50% of the way towards a more robust `fork_revert` module.

## TODO

- [ ] Fix fork_revert logic
- [ ] Basic test (single version)
- [ ] Comprehensive test (multiple versions)

**Comment by danielrachi1** [comment]
I'd like to work on this issue. I have a few questions before I start:

Are there any existing tests for the fork revert logic? I didn't find anything under the beacon chain tests. I think I would need to implement at least one of the proposed tests before fixing the `fork_revert` module.

If I understood correctly, I could implement a test that checks if the current version of Lighthouse can revert a fork missed by the same version without having to wait for #3807 to be merged. So writing this (local and for CI) could be a good place to start. What do you think?

**Comment by michaelsproul** [comment]
@danielrachi You're right that there aren't any existing tests for `fork_revert`. A good first step would be to write one, maybe in `beacon_chain/tests`. You're right that you won't need the local testnet stuff from #3807 in order to do it

**Comment by danielrachi1** [comment]
I'm no longer working on this issue. If anyone else is interested, feel free to take it.

**Comment by danielrachi1** [comment]
I'm re-taking this issue. I'll open a PR as soon as I have progress to show. 🫡

**Comment by danielrachi1** [comment]
I am no longer working on this issue. 😬

**Comment by danielrachi1** [comment]
Actually... I'll give this another try. I'll open a new PR when I have something to show.

**Comment by danielrachi1** [comment]
I've been looking into this issue. I have a general idea of what to do:

### Single version test

1. Write a new simulation in `testing/simulator/src/fork_revert_sim.rs`.
2. Add this new simulation to CI, in `.github/workflows/test-suite.yml`.

I could use the existing simulations: `basic_sim.rs` and `fallback_sim.rs`. As a guide.

### Multi version test

1. Write a new script in `scripts/tests/fork_revert.rs`.
2. Add this new script to CI, in `.github/workflows/local-testnet.yml`

There are 3 existing scripts in `scripts/tests/` to guide me.

The hardest part of this will probably be figuring out how to get a different version of Lighthouse available on the script. First guess: docker can help.
 
### Logic fix

With the tests completed, fixing the logic should be straightforward. I'll need to dive into `beacon_node/beacon_chain/src/fork_revert.rs` and see what's wrong.

**Comment by danielrachi1** [comment]
🤦  Turns out there's a beacon chain test for this exact purpose:

https://github.com/sigp/lighthouse/blob/ced49dd265e01ecbf02b12073bbfde3873058abe/beacon_node/beacon_chain/tests/store_tests.rs#L3595

However, it always passes. There's a hint on why it might be broken:

https://github.com/sigp/lighthouse/pull/2529#discussion_r696801178

---

I don't see any reason why `revert_minority_fork_on_resume` would be fundamentally broken. I think I can keep the general flow of the test and fix it to make it work with every hardfork. That would give us the single version test.

If that works, reproducing `revert_minority_fork_on_resume` on Kurtosis shouldn't be too hard. Even with multiple versions. Kurtosis suports arbitrary docker images to be run on the testnets.

---

~Before diving there, I want to ask:~

~@michaelsproul is `revert_minority_fork_on_resume` _fundamentally_ broken?~

~I mean, are there any known reasons why it would be necessary to fully rewrite that test, instead of patching it to work with all hardforks? (Right now it only works with altair, I think.)~

~Any other comments you can provide on this approach? :)~

Nevermind, I just went with it.

**Comment by danielrachi1** [comment]
Tried to duplicate the test in Kurtosis and it was... harder than expected.

---

Sadly, I've lost the interest I once had for this problem. I've been trying to push through it because I wanted to avoid the embarrassment of quitting after so long. But I've realized this issue requires a different skill set or perspective than I currently have.

It would be better for everyone if someone with more interest and skill solved it.

I'm sorry.

---

cc @michaelsproul please unassign me from this issue. 🥲

**Comment by michaelsproul** [comment]
Putting fork_revert in the bin for now:

- https://github.com/sigp/lighthouse/pull/8891

If we keep this issue open, someone could revive the code from the git history.
