### ISSUE TITLE
PeerDAS - Tracking Issue

### ISSUE THREAD

**Issue by AgeManning** [sigp/lighthouse#4983]
## Description

This is a tracking issue for the work that is being undertaken on building out Data Availability Sampling.

This will be updated and edited as we go.

Instructions for running a DAS devnet can be found in [this gist](https://gist.github.com/jimmygchen/54574443ea8a94118f0f748b69a5e610).

Main PR to `unstable`: 
- #5683 

## Devnet 5

- [x] #6251
- [ ] #6258
- [x] #5990 
- [x] #6268 
- [x] #5894
- [x] #6111
- [x] #6018 
- [x] #6107 
- [ ] Implement validator custody ([spec](https://github.com/ethereum/consensus-specs/pull/3779)) https://github.com/sigp/lighthouse/issues/6767
- [x] https://github.com/sigp/lighthouse/issues/6854
- [ ] Address all `TODO(das)` comments
- [ ] Batch verify KZG proofs where possible https://github.com/sigp/lighthouse/pull/6851
- [x] Don't lookup sync individual columns received from gossip. WIP  [`dapplion:dedup-columns-by-root-requests`](https://github.com/sigp/lighthouse/compare/unstable...dapplion:lighthouse:dedup-columns-by-root-requests?expand=1)

## `TODO(das)`

- Collection of small / easy TODOs https://github.com/sigp/lighthouse/pull/6862
- https://github.com/sigp/lighthouse/pull/6850

### Data format and distribution (#5050)

- [x] Add `ColumnSidecar` type 
- [x] Extend blobs horizontally with dummy data (`0x{random_uniq_bits}...{col_id}`) and distribute to column subnets
- [x] Create 32 column subnets `NUM_COLUMN_SUBNETS`
- [x] Compute subnets to subscribe to based on `node_id` (see att example [here](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/p2p-interface.md#attestation-subnet-subscription))
- [x] Node to subscribe to only `CUSTODY_REQUIREMENT` column subnets

### Data Column Custody

- [x] #5196
- [x] Advertise extra custodied columns through ENR (@jacobkaufmann)
- [x] Implement `PEERDAS_ACTIVATION_EPOCH` to transition from deneb blobs to data columns (@jimmygchen)
- [x] #5570
- [x] #5684
- [x] ❌ Proposer to store all data columns to prevent data loss (See [this comment](https://github.com/sigp/lighthouse/pull/5570#discussion_r1575807617)) - increase peer count and custody requirement instead

### Sampling

- [x] #5196
- [x] #5616
- [x] #5569
- [ ] Don't attempt downloading sample for custody columns already in DB
- [x] #6929
- [x] #6930

### Syncing

- [x] #5353
- [x] #5747
- [x] #5776

### Misc 

- [x] #5210
- [x] #5701
- [x] ❌ #5734
- [x]  #5772 
- [x]  #5750
- [x] #5781 
- [x] #5783
- [x] #5779
- [x] #5805 
- [x] #5828
- [x] #5890

### `peerdas-devnet-1`

- [x] #5950 

### `peerdas-devnet-2`

- [x] #6233
- [x] #6289 

### `peerdas-devnet-3`

- [x] #6072 
- [x] #6026
- [x] #6109

### Post-Pectra (Sampling, 2D PeerDAS etc)

- [ ] Update fork choice with sampling results ([spec](https://github.com/ethereum/consensus-specs/pull/3779))
- [x] #6110 

## Current behaviour not specified by consensus-specs

- _Only supernode_ performs reconsturctions once >50% of columns received
- LossyDAS implementation
- Re-process `DataColumnsByRoot` requests and respond when columns are ready

**Comment by jimmygchen** [comment]
I'm closing this one as most items from the initial list have been completed, and the remaining tasks have either been converted into issue or are no longer necessary (please correct me if I'm wrong @dapplion). 

To see the full list of PeerDAS issues, use the `das` label:
https://github.com/sigp/lighthouse/issues?q=state%3Aopen%20label%3A%22das%22

To see the list of PeerDAS issues required for the fulu fork, use the `fulu` label filter:
https://github.com/sigp/lighthouse/issues?q=state%3Aopen%20label%3A%22fulu%22
