### ISSUE TITLE
MaxEB - tracking issue

### ISSUE THREAD

**Issue by dapplion** [sigp/lighthouse#5399]
## Description

Tracking issue for potential Electra feature [EIP-7251: Increase the MAX_EFFECTIVE_BALANCE](https://eips.ethereum.org/EIPS/eip-7251).

- Reference spec: https://github.com/ethereum/consensus-specs/pull/3618

### Approach an assumptions

- Currently building on Deneb

### Progress

- [ ] "Core" MaxEB logic (everything except features below)
- [ ] Execution partial withdrawals
- [ ] In-protocol consolidations

**Comment by michaelsproul** [comment]
Complete
