### ISSUE TITLE
FOCIL - Tracking Issue

### ISSUE THREAD

**Issue by eserilev** [sigp/lighthouse#6660]
## Description

This is a tracking issue for the work being done to build out Fork-Choice Enforced Inclusion Lists (FOCIL) 

Spec:

- https://github.com/ethereum/consensus-specs/pull/4003

Branch: https://github.com/sigp/lighthouse/tree/electra-focil

I've tried breaking up the changes into separate tasks. This list should be edited/updated as we go

## Beacon Chain
- [x] Add `get_inclusion_list_committee`
- [ ] Query IL from EL

## Engine API
- [x] Check for `getInclusionListV1` engine capability
- [x] Make RPC request for `getInclusionListV1`
- [ ] Add IL to new payload request

## Beacon API
- [x] Endpoint to retrieve IL duties
- [ ] Support requests for historical IL duties
- [ ] Endpoint to retrieve IL corresponding to IL duty
- [ ] Endpoint to broadcast signed IL

## Validator Client
- [x] Poll beacon node for IL duties
- [x] Keep track of IL duties
- [ ] Query IL from beacon node to sign and broadcast

## P2P
- [x] IL gossip-sub topic
- [ ] Fully implement gossip verification logic
- [x] Keep track of IL equivocations
- [x] Handle IL gossip message

## Fork Choice

- [x] https://github.com/sigp/lighthouse/issues/6802 @eserilev 

## Tests
- [ ] TODO

## Misc
- [ ] More comprehensive error handling
- [ ] More comprehensive metrics
