### ISSUE TITLE
100k validators on t2.mediums

### ISSUE THREAD

**Issue by paulhauner** [sigp/lighthouse#847]
## Description

Our latest testnet is running 8x validator nodes on AWS t2.medium nodes (2-vCPU, 4GB RAM), each with 12.5k validators. These nodes ran fine for the first 24hrs but then started to crumble when the network experienced instability. What I observe is that the nodes get full CPU utilization and are unable to clear their work queue (incoming attestations, blocks, API calls, etc) and get stuck in a bit of a spiral of falling behind and producing fork blocks. There are also occasions where nodes run out of RAM and the OS kills the processes.

I think there are a several issues leading to these problems. I've made a list of the tasks I think we need to focus on to ensure we can have stability when running 100k validators on t2.mediums:

- [ ] **Optimize the `BeaconChain::persist` function (#851):** this is taking several seconds (even minutes) on the AWS nodes. Storing everything, all at once, every block is how we do it now and unsurprisingly we need to find a more nuanced way to do this.
- [ ] **Revisit the way we cache `BeaconState` (related: #850):** the caches we're using in `Store` are very liberal about what gets added into the LRU cache so I think we're seeing the caches getting washed out by syncing iterators and migrations leaving `per_block_processing` and `find_head` to load from disk.
- [ ] **Reconsider our approach to caching decompressed validator public keys (#848):** Presently each pubkey stores the compressed bytes and optionally the decompressed bytes and we use `BeaconState::decompress_validator_pubkeys` to iterate through all of them and build them. This is very expensive on a low-spec machine with 100k validators (several seconds). When we combine this with the above caching issue, we're seeing either (a) really long times to decompress all the keys at once or (b) very slow block processing verification because it needs to decompress each key.
- [ ] **Reduce memory usage:** The 4gb nodes are at a bit of knifes-edge regarding memory usage, I've seen a few nodes run our of RAM and kill `lighthouse`. I suspect that caching and holding-in-memory `BeaconStates` is what's eating our RAM (I did some **rough** experiments and found that keeping one beacon state with fully-build caches in memory takes ~110mb of physical RAM). Now that we have attestation caches (#841) that rarely need to read `BeaconState`, I think we can make our caches targeted towards block processing; we can store fewer of them and we can mutate them as we receive new blocks (reducing copies and therefore states held in memory).
- [ ] **Improve the threading model:** presently we're blocking the tokio executor with long-running tasks. This means we start timing out on API and p2p calls. We definitely need to switch over to the new tokio runtime so we can utilize a blocking thread-pool. We may also want to consider introducing specialized threadpools for blocks/attestations so we can have some control over how big those queues get to help with performance and DoS hardening. (e.g., give us the ability to start dropping attestations if we have more than `n` already queued). Note: this is a bit of longer-term goal and I don't think will be immediately necessary if we can solve the above issue.

To action these, I think we can split each one off into new issues/PRs. Ofc, keen to hear thoughts/suggestions.

**Comment by AgeManning** [comment]
For the threading model, if there are expensive long-running tasks, for now we can simply spawn whatever task as an OS thread rather than using the executor. I've done this currently in syncing. 

Once we've shifted to stable futures, it won't be difficult to spawn the OS thread back to a blocking thread on the executor.

**Comment by paulhauner** [comment]
Closing this since a lot has changed and I don't think most of this is really relevant anymore.
